feat: don't show new conversation when in custom view
BiteSpeed-Dev/chatwoot pull request #15
Opened 2024-01-31 19:20 UTC by cyprusad

# Pull Request Template

## Description

Don't add new conversations when in a custom view (active folder view)

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality not to work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Local testing

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2024-02-08 03:46 UTC, pranavrajs commented on app/javascript/dashboard/components/ChatList.vue
> +        this.$store.dispatch('setHasActiveFolder');
I would suggest setting the id rather than a boolean, so that this can be used later.

2024-02-08 03:47 UTC, pranavrajs commented on app/javascript/dashboard/components/ChatList.vue
> +        return true;
This entire block is written in a computed property. Can you please move this mixins?

2024-02-08 03:49 UTC, pranavrajs requested changes
Some comments on the implementation. Please take a look at the individual comments.x

2024-02-08 03:49 UTC, pranavrajs commented on app/javascript/dashboard/store/modules/conversations/index.js
> +  hasActiveFolder: false,
Another way of doing this is to avoid adding the conversations if you are on the folder view (Check if the route matches the folder path). This way, there is no need to add any state.

2024-02-08 03:49 UTC, pranavrajs commented on app/javascript/dashboard/store/modules/conversations/index.js
> +  hasActiveFolder: false,
Please check the `isOnMentionsView` method implementation and it's usage.

2024-02-08 21:05 UTC, cyprusad commented on app/javascript/dashboard/store/modules/conversations/index.js
> +  hasActiveFolder: false,
@pranavrajs this was a great tip, thanks!

2024-02-08 21:05 UTC, cyprusad commented on app/javascript/dashboard/components/ChatList.vue
> +        this.$store.dispatch('setHasActiveFolder');
used the action helper approach, so this point is moot now, resolving conversations about this code block

2024-02-10 22:18 UTC, pranavrajs approved these changes
Looks good to me. Please test this out before merging.

2024-02-10 22:18 UTC, pranavrajs commented
@cyprusad On a side note, if you can raise this against Chatwoot main branch, that would be helpful for us.

2024-02-11 04:37 UTC, cyprusad commented
@pranavrajs done https://github.com/chatwoot/chatwoot/pull/8905

Please advise on next steps:
- does the PR just get merged in upstream and then someone from your team syncs Bitespeed's commits with upstream and deploy that (probably makes the most sense, if this is needed by upstream anyway)
- should I merge this PR and expect that to be deployed by someone from your team?

2024-02-14 05:41 UTC, pranavrajs commented
@cyprusad You can close this PR and take a down merge from develop.

2024-02-14 15:02 UTC, closed without merging