feat: groupBy preserved to allow for detailed agent report exports
BiteSpeed-Dev/chatwoot pull request #16
Opened 2024-02-01 20:24 UTC by cyprusad

# Pull Request Template

## Description

Agent report exports will be more detailed

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality not to work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration.

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2024-02-01 21:23 UTC, cyprusad commented
Sample agent report export
```csv
Reporting period 2024-01-26 to 2024-02-02
 
  Conversation Count

  Date,John,David

  January 26 2024,0,0

  January 27 2024,0,0

  January 28 2024,0,0

  January 29 2024,0,0

  January 30 2024,15,0

  January 31 2024,17,0

  February 01 2024,0,0

  February 02 2024,0,0

  

  Unattended Conversations Count

  Date,John,David

  January 26 2024,0,0

  January 27 2024,0,0

  January 28 2024,0,0

  January 29 2024,0,0

  January 30 2024,13,0

  January 31 2024,12,0

  February 01 2024,0,0

  February 02 2024,0,0

  

  Incoming Messages Count

  Date,John,David

  January 26 2024,0,0

  January 27 2024,0,0

  January 28 2024,0,0

  January 29 2024,0,0

  January 30 2024,0,0

  January 31 2024,0,0

  February 01 2024,0,0

  February 02 2024,0,0

  

  Outgoing Messages Count

  Date,John,David

  January 26 2024,0,0

  January 27 2024,0,0

  January 28 2024,0,0

  January 29 2024,0,0

  January 30 2024,0,0

  January 31 2024,2,0

  February 01 2024,6,0

  February 02 2024,0,0

  

  Avg First Response Time (in minutes)

  Date,John,David

  January 26 2024,0,0

  January 27 2024,0,0

  January 28 2024,0,0

  January 29 2024,0,0

  January 30 2024,0,0

  January 31 2024,0,0

  February 01 2024,2028,0

  February 02 2024,0,0

  

  Avg Resolution Time (in minutes)

  Date,John,David

  January 26 2024,0,0

  January 27 2024,0,0

  January 28 2024,0,0

  January 29 2024,0,0

  January 30 2024,0,0

  January 31 2024,0,0

  February 01 2024,1946,0

  February 02 2024,0,0

  

  Resolutions Count

  Date,John,David

  January 26 2024,0,0

  January 27 2024,0,0

  January 28 2024,0,0

  January 29 2024,0,0

  January 30 2024,0,0

  January 31 2024,0,0

  February 01 2024,2,0

  February 02 2024,0,0

  

  Reply Time (in minutes)

  Date,John,David

  January 26 2024,0,0

  January 27 2024,0,0

  January 28 2024,0,0

  January 29 2024,0,0

  January 30 2024,0,0

  January 31 2024,0,0

  February 01 2024,0,0

  February 02 2024,0,0
```

2024-02-08 03:51 UTC, pranavrajs commented on app/helpers/api/v2/accounts/reports_helper.rb
> +module Api::V2::Accounts::ReportsHelper # rubocop:disable Metrics/ModuleLength
Can you please re-write this with using service objects? Disabling rubocop is not a good step here.

2024-02-08 03:52 UTC, pranavrajs requested changes
I can do a review once the methods are rewritten according to the rubocop guidelines.

2024-02-08 22:18 UTC, cyprusad commented
@pranavrajs Could use another round of review to get a vetting of the approach throughout

2024-02-09 01:08 UTC, cyprusad commented on app/views/api/v2/accounts/reports/agents.csv.erb
> +  <%= CSV.generate_line row %>
if the presenter approach taken is good, then potentially can split this view into partials for the individual section of the reports if needed to get the i18n strings etc. though it might be overkill if this is used only at Bitespeed and not intended to be merged back into the chatwoot fork.

also had some weird white spacing issues when using `CSVSafe` so reverted to `CSV`

2024-02-09 01:09 UTC, cyprusad commented on app/presenters/reports/exportable_agent_report_presenter.rb
> +    sample_agent_report = agent_reports.values.first
this is needed to get the general structure of the reports and generate the individual report headers etc. below

2024-02-09 01:12 UTC, cyprusad commented on app/presenters/reports/exportable_agent_report_presenter.rb
> +      # Prepare data rows for each date
the logic that follows converts the reports created in the report builder and aggregated in [`#detailed_report`]()     into the format needed by Bitespeed customers given here https://github.com/BiteSpeed-Dev/chatwoot/pull/16#issuecomment-1922271327

2024-02-15 01:05 UTC, pranavrajs reviewed
@cyprusad To meet the expectation of retrieving the results in a single API call, it would require more than just querying. I would recommend considering options such as caching the results before hand or sending the reports asynchronously using sidekiq workers. 
The approach described here may not be effective for all cases we encounter. The queries may work well for a small number of messages, but we need to consider the scenario where the account has over 100,000 messages every month. Please test the approach with this larger volume of messages and see if it still produces the desired output.

2024-02-15 01:05 UTC, pranavrajs commented on app/builders/v2/report_builder.rb
> +  end
Putting this in a single method would not work due to the huge number of messages, reply_time events.

2024-02-16 16:33 UTC, cyprusad commented
@pranavrajs so I am piggybacking off the existing report builder and using the `build` and `timeseries` methods to create the detailed report. In fact, mostly the only difference is that instead of calling `summary` on it like the other API endpoints that generate the reports currently, I am just returning the report as is for the most part. So the API endpoint is already generating this and rendering it in the frontend. I am basically just allowing for CSV exports to also be able to use it. Is that still a deal breaker you reckon?

2024-02-24 16:41 UTC, closed without merging